#pragma once
#include "commands.hpp"

namespace helpme {

inline std::vector<Commands> commandList = {
    Commands{"apt",
             "Advanced Package Tool",
             {"apt-get update", "#Update package database",
              "apt-get install package", "#Install package",
              "apt-get remove package", "#Remove package", "apt-get upgrade",
              "#Upgrade package"}},
    Commands{"awk",
             "Pattern scanning and text processing",
             {"awk '{print $1}' file", "#Print first field",
              "awk -F: '{print $1}' file", "#Set field separator",
              "awk 'NR==1' file", "#Print first line", "awk '/pattern/' file",
              "#Print matching lines", "awk '{sum+=$1} END {print sum}' file",
              "#Sum values"}},
    Commands{"chmod",
             "Change file mode bits",
             {"chmod 755 file", "#Set permissions", "chmod u+x file",
              "#Add execute for user", "chmod -R 644 dir", "#Recursive change",
              "chmod a+r file", "#Readable for all", "chmod g-w file",
              "#Remove group write"}},
    Commands{"chown",
             "Change file owner and group",
             {"chown user file", "#Change owner", "chown user:group file",
              "#Change owner and group", "chown -R user dir",
              "#Recursive change", "chown :group file", "#Change group only",
              "chown --reference=file1 file2", "#Copy ownership"}},
    Commands{"cp",
             "Copy files and directories",
             {"cp file1 file2", "#Copy file1 to file2", "cp -r dir1 dir2",
              "#Copy directory recursively", "cp -i file1 file2",
              "#Interactive (confirm overwrite)", "cp -p file1 file2",
              "#Preserve attributes", "cp -v file1 file2", "#Verbose output"}},
    Commands{"curl",
             "Transfer data from or to a server",
             {"curl url", "#Get content", "curl -o file url", "#Save to file",
              "curl -I url", "#Headers only", "curl -d 'data' url",
              "#POST data", "curl -u user:pass url", "#Basic auth"}},
    Commands{"df",
             "Report filesystem disk space usage",
             {"df -h", "#Human readable sizes", "df -i", "#Show inodes info",
              "df -T", "#Show filesystem type", "df --total", "#Show total",
              "df -x tmpfs", "#Exclude filesystem type"}},
    Commands{"diff",
             "Compare contents of files",
             {"diff file1 file2", "#Compare files", "diff -y file1 file2",
              "#Side by side", "diff -u file1 file2", "#Unified diff"}},
    Commands{"du",
             "Report disk usage for files and directories",
             {"du -h", "#Human readable sizes", "du -s", "#Summarize",
              "du -h --max-depth=2", "#Max depth 2", "du -h --max-depth=0",
              "#Current directory only", "du -h --total", "#Show total"}},
    Commands{"dmesg",
             "Print or control kernel ring buffer",
             {"dmesg", "#Show kernel messages", "dmesg -H", "#Human readable",
              "dmesg -l err", "#Show only errors", "dmesg -w",
              "#Follow new messages", "dmesg -T", "#Show human readable time"}},
    Commands{"find",
             "Search for files in directory hierarchy",
             {"find . -name \"*.txt\"", "#Find .txt files", "find . -type d",
              "#Find directories", "find . -mtime -7",
              "#Modified in last 7 days", "find . -size +100M",
              "#Files over 100MB", "find . -exec ls -l {}",
              "#Execute command on results"}},
    Commands{"fd",
             "A faster alternative to find",
             {"fd 'foo' /bar", "#Find 'foo' in /bar", "fd 'foo' /bar -r",
              "#Recursive search", "$fd --exclude pattern --type files foo",
              "#Search files excluding pattern"}},
    Commands{"free",
             "Display amount of free and used memory",
             {"free -h", "#Human readable sizes", "free -s 5",
              "#Update every 5 seconds", "free -t", "#Show total",
              "free -w          # Wide output", "free -m",
              "#Show in megabytes"}},
    Commands{"grep",
             "Search text patterns in files",
             {"grep pattern file", "#Search for pattern in file",
              "grep -r pattern dir", "#Recursive search in directory",
              "grep -i pattern file", "#Case-insensitive search",
              "grep -v pattern file", "#Invert match", "grep -n pattern file",
              "#Show line numbers"}},
    Commands{"ip",
             "Show/manipulate routing, network devices, interfaces",
             {"ip addr", "#Show addresses", "ip link",
              "#Show network interfaces", "ip route", "#Show routing table",
              "ip neigh", "#Show neighbor table", "ip -s link",
              "#Show interface statistics"}},
    Commands{"kill",
             "Terminate processes",
             {"kill pid", "#Terminate process", "kill -9 pid",
              "#Force terminate", "kill -l", "#List signal names",
              "killall process", "#Kill by process name", "pkill pattern",
              "#Kill matching processes"}},
    Commands{"ls",
             "List directory contents",
             {"ls -l", "#Detailed list format", "ls -a", "#Show hidden files",
              "ls -lh", "#Human readable sizes", "ls -R", "#Recursive listing",
              "ls -lt", "#Sort by time modified"}},
    Commands{"mv",
             "Move/rename files and directories",
             {"mv file1 file2", "#Move/rename file1 to file2",
              "mv -i file1 file2", "#Interactive (confirm overwrite)",
              "mv -n file1 file2", "#No overwrite", "mv file1 dir/",
              "#Move file to directory", "mv -v * ../dir/",
              "#Move all files verbose"}},
    Commands{"netstat",
             "Network statistics",
             {"netstat -a", "#Show all sockets", "netstat -t",
              "#TCP connections", "netstat -l", "#Listening ports",
              "netstat -p", "#Show PIDs", "netstat -r", "#Show routing table"}},
    Commands{"nice",
             "Run a program with modified scheduling priority",
             {"nice command", "#Run with default nice value",
              "nice -n 10 command", "#Run with specified nice value",
              "nice -n -10 command", "#Need root for negative",
              "renice 10 -p pid", "#Change running process",
              "nice -n 10 ./script.sh", "#Run script with nice"}},
    Commands{"nohup",
             "Run a command immune to hangups",
             {"nohup command &", "#Run in background", "nohup ./script.sh &",
              "#Run script in background", "nohup command > out.log &",
              "#Redirect output", "nohup command & disown",
              "#Background and disown", "nohup ./long_task.sh &",
              "#Long running task"}},
    Commands{"pacman",
             "Package management (Arch-based)",
             {"pacman -S pkg", "#Install package", "pacman -Syu",
              "#Update system", "pacman -Rs pkg", "#Remove package",
              "pacman -Ss pkg", "#Search packages", "pacman -Qi pkg",
              "#Query package info", "$pacman -Rsn $(pacman -Qtdq)",
              "#Remove orphaned packages"}},
    Commands{"ping",
             "Test network connectivity",
             {"ping host", "#Ping host", "ping -c 4 host   # Ping 4 times",
              "ping -i 2 host", "#Ping every 2 seconds", "ping -s 100 host",
              "#Set packet size", "ping -W 2 host",
              "#Timeout after 2 seconds"}},
    Commands{"ps",
             "Report process status",
             {"ps aux", "#Show all processes", "ps -ef", "#Full format listing",
              "ps --forest", "#Show process hierarchy", "ps -u username",
              "#User's processes", "ps -p pid", "#Show specific process"}},
    Commands{"rm",
             "Remove files or directories",
             {"rm file", "#Remove file", "rm -r dir",
              "#Remove directory recursively", "rm -f file",
              "#Force remove without confirm", "rm -i file",
              "#Interactive removal", "rm -rf dir", "#Force remove directory"}},
    Commands{"sed",
             "Stream editor for filtering and transforming text",
             {"sed 's/old/new/' file", "#Replace first match",
              "sed 's/old/new/g' file", "#Replace all matches",
              "sed -i 's/old/new/' file", "#Edit file in place",
              "sed '1d' file", "#Delete first line", "sed '/pattern/d' file",
              "#Delete matching lines"}},
    Commands{"ss",
             "Another utility to investigate sockets",
             {"ss", "#Show all connections", "ss -t", "#Show TCP connections",
              "ss -l", "#Show listening sockets", "ss -p",
              "#Show processes using sockets", "ss -s", "#Print statistics"}},
    Commands{"systemctl",
             "Control the systemd system and service manager",
             {"systemctl status service", "#Check service status",
              "systemctl start service", "#Start service",
              "systemctl stop service", "#Stop service",
              "systemctl enable service", "#Enable at boot",
              "systemctl restart service", "#Restart service"}},
    Commands{"systemd-analyze",
             "Analyze the systemd unit files",
             {"systemd-analyze verify /etc/systemd/system/foo.service",
              "#Verify the systemd unit file"}},
    Commands{"tar",
             "Archive utility",
             {"tar cvf archive.tar file1 file2", "#Create archive",
              "tar xvf archive.tar", "#Extract archive",
              "tar zcvf archive.tar.gz file1 file2", "#Compress archive"}},
    Commands{"timedatectl",
             "Control the system time and date",
             {"timedatectl status", "#Show current settings",
              "timedatectl set-time '2020-01-01'", "#Set date",
              "timedatectl set-timezone UTC", "#Set timezone",
              "timedatectl set-ntp true", "#Enable NTP",
              "timedatectl list-timezones", "#Show timezones"}},
    Commands{"top",
             "Dynamic real-time view of processes",
             {"top", "#Interactive process viewer", "top -u user",
              "#Show user's processes", "top -p pid",
              "#Monitor specific process", "top -d 5",
              "#Update every 5 seconds", "top -o %MEM",
              "#Sort by memory usage"}},
    Commands{"uname",
             "Print system information",
             {"uname -a", "#All system information", "uname -r",
              "#Kernel release", "uname -m", "#Machine hardware", "uname -n",
              "#Network hostname", "uname -p", "#Processor type"}},
    Commands{"unzip",
             "Extract files from zip archives",
             {"unzip archive.zip", "#Extract archive",
              "unzip archive.zip -d dir", "#Extract to directory"}},
    Commands{"useradd",
             "Create a new user",
             {"useradd username", "#Create user", "useradd -m username",
              "#Create home directory", "useradd -G group user",
              "#Add to groups", "useradd -s /bin/bash user", "#Set shell",
              "useradd -c \"Comment\" user", "#Add comment"}},
    Commands{"usermod",
             "Modify a user account",
             {"usermod -aG group user", "#Add to group", "usermod -L user",
              "#Lock account", "usermod -U user", "#Unlock account",
              "usermod -s /bin/bash user", "#Change shell",
              "usermod -d /new/home user", "#Change home"}},
    Commands{"userdel",
             "Delete a user account",
             {"userdel user", "#Delete user", "userdel -r user",
              "#Remove home directory"}},
    Commands{"users",
             "List users",
             {"users", "#List users", "users | wc -w", "#Count users"}},
    Commands{"wget",
             "Download files from the web",
             {"wget http://example.com/file.txt", "#Download file",
              "wget --recursive http://example.com/dir", "#Download dir"}},
    Commands{"whoami",
             "Print the name of the current user",
             {"whoami", "#Print username"}},
    Commands{"whois",
             "Lookup information about a domain or IP address",
             {"whois example.com", "#Lookup domain"}}};
} // namespace helpme
